build:
  version: "1.0"

accounts:
  message: "Welcome to EasyBank accounts related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@easybank.com"
  oncallSupport:
    - (33) 698765433
    - (33) 667584922