build:
  version: "3.0"

cards:
  message: "Welcome to EasyBank cards related local APIs"
  contactDetails:
    name: "Raed Ghodhbane - Developer"
    email: "raed@easybank.com"
  oncallSupport:
    - (33) 633333454
    - (33) 644444567
